import i18n from "i18next";
import { initReactI18next } from "react-i18next";
import LanguageDetector from "i18next-browser-languagedetector";

import enCore from "./locales/en.core.json";

/**
 * LOCALE LOADING — and English is no longer the exception.
 *
 * `en.json` is 305 KB raw, about 86 KB gz, and importing it here put all 107
 * namespaces in front of the first paint for every visitor. It was the single
 * largest item in the entry: dropping it takes the shell from 326.5 KB gz to
 * 245.2 KB, which is what finally puts routes under the 250 KB budget.
 *
 * It cannot just be made lazy. i18next renders the KEY when a translation is
 * missing, so a page that paints before its bundle arrives shows `nav.home` to
 * the user — a worse defect than the one being fixed.
 *
 * So the split is by WHEN IT IS NEEDED, derived rather than guessed:
 *
 *   - `en.core.json` (2.3 KB) holds the namespaces used by modules the shell
 *     reaches WITHOUT crossing a dynamic import. Today that is exactly one:
 *     `gdpr`, for the cookie banner. It is generated by
 *     scripts/i18n/build-core.mjs, which walks the real module graph, and
 *     src/test/perf/i18nCore.test.ts fails CI if it goes stale.
 *   - everything else arrives with the full bundle, which is loaded
 *     immediately at boot and awaited by `localeReady`. Every page in this app
 *     is already lazy and already waits behind `<Suspense fallback={PageLoader}>`,
 *     so the wait is one that was there anyway.
 *
 * `es` / `nl` were already lazy and are unchanged.
 */
const LAZY_LOCALES: Record<string, () => Promise<{ default: object }>> = {
  en: () => import("./locales/en.json"),
  es: () => import("./locales/es.json"),
  nl: () => import("./locales/nl.json"),
};

const loadedLanguages = new Set<string>();

async function loadLocale(lng: string): Promise<void> {
  const base = lng.split("-")[0];
  if (loadedLanguages.has(base) || !LAZY_LOCALES[base]) return;
  const data = (await LAZY_LOCALES[base]()).default;
  i18n.addResourceBundle(base, "translation", data, true, true);
  loadedLanguages.add(base);
  // If this is still the active language, re-emit languageChanged so
  // react-i18next re-renders with the real translations (it rendered the
  // en fallback while the bundle was in flight).
  if (i18n.language?.split("-")[0] === base) {
    void i18n.changeLanguage(i18n.language);
  }
}

// Audit hook: when the page-audit harness sets window.__AUDIT__ before boot,
// collect every missing translation key so specs can assert zero. No-op in
// production (the flag is never set there). See e2e/helpers/pageAudit.ts.
const auditMode =
  typeof window !== "undefined" &&
  (window as unknown as { __AUDIT__?: boolean }).__AUDIT__ === true;

// Initialize i18n synchronously to prevent race conditions
i18n
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    resources: { en: { translation: enCore } },
    partialBundledLanguages: true,
    fallbackLng: "en",
    supportedLngs: ["en", "es", "nl"],
    saveMissing: auditMode,
    missingKeyHandler: auditMode
      ? (lngs, _ns, key) => {
          // Only record once the language's bundle is actually loaded —
          // otherwise every key looks "missing" during the async load.
          const lng = (lngs?.[0] ?? i18n.language ?? "en").split("-")[0];
          if (!loadedLanguages.has(lng)) return;
          const w = window as unknown as { __I18N_MISSING__?: string[] };
          (w.__I18N_MISSING__ ||= []).push(key);
        }
      : undefined,
    interpolation: {
      escapeValue: false,
    },
    detection: {
      order: ["localStorage", "navigator", "htmlTag"],
      caches: ["localStorage"],
      lookupLocalStorage: "i18nextLng",
    },
    // Ensure synchronous initialization
    initImmediate: false,
    react: {
      useSuspense: false, // Disable suspense to prevent issues with lazy-loaded components
    },
  });

/**
 * Resolves once the active language's full bundle is in place — and English's
 * too, because English is the fallback every other language falls through to.
 *
 * `App` holds route rendering behind this. Without it a route chunk that arrives
 * before the locale paints its keys instead of its words, which is exactly the
 * regression this file's split could otherwise introduce.
 */
export const localeReady: Promise<void> = (async () => {
  const active = (i18n.language ?? "en").split("-")[0];
  await Promise.all([loadLocale("en"), active === "en" ? Promise.resolve() : loadLocale(active)]);
})();

// Lazy-load on every future language switch.
i18n.on("languageChanged", (lng) => {
  void loadLocale(lng);
});

export default i18n;
