import { describe, it, expect } from "vitest";
import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { stripComments } from "../helpers/stripComments";

/**
 * ENGLISH IS NO LONGER IN THE ENTRY BUNDLE, and this is what makes that safe.
 *
 * `src/i18n/index.ts` imported `en.json` statically: 305 KB raw, ~86 KB gz, all
 * 107 namespaces, in front of the first paint for every visitor. It was the
 * largest single item in the shell — removing it took the entry from 326.5 KB gz
 * to 246.0, which is what brings routes within reach of the 250 KB budget.
 *
 * The danger is specific and user-visible: i18next renders the KEY when a
 * translation is missing. A component that paints before its bundle arrives
 * shows `nav.home` instead of "Home". Trading a slow page for a broken-looking
 * one is not a performance win.
 *
 * Two things prevent it, and both are asserted here:
 *
 *   1. `en.core.json` carries every namespace used by modules the shell reaches
 *      WITHOUT crossing a dynamic import — generated by walking the real module
 *      graph, so it cannot drift out of step with an import somebody adds.
 *   2. `LocaleGate` in App.tsx holds route rendering until the full bundle has
 *      landed, behind the `<PageLoader />` those lazy routes already showed.
 *
 * Everything past a dynamic import is a route chunk and is covered by (2).
 * Everything before one is covered by (1). The gap between them is what these
 * assertions exist to keep closed.
 */

const ROOT = path.resolve(__dirname, "../../..");
const read = (rel: string) => fs.readFileSync(path.join(ROOT, rel), "utf8");

describe("the eager locale core", () => {
  it("is exactly what the module graph says it must be", () => {
    // The generator IS the check: --check re-derives the core from source and
    // exits non-zero if the committed file differs. Running it here means a new
    // eager import that needs a namespace fails in CI rather than shipping a raw
    // key to a visitor.
    expect(() =>
      execFileSync("node", ["scripts/i18n/build-core.mjs", "--check"], {
        cwd: ROOT,
        encoding: "utf8",
        stdio: ["ignore", "pipe", "pipe"],
      }),
    ).not.toThrow();
  });

  it("is a small fraction of the full bundle, or it has stopped being a core", () => {
    const core = fs.statSync(path.join(ROOT, "src/i18n/locales/en.core.json")).size;
    const full = fs.statSync(path.join(ROOT, "src/i18n/locales/en.json")).size;
    expect(core).toBeLessThan(full * 0.05);
  });

  it("holds only namespaces that really exist in en.json", () => {
    const core = JSON.parse(read("src/i18n/locales/en.core.json")) as Record<string, unknown>;
    const en = JSON.parse(read("src/i18n/locales/en.json")) as Record<string, unknown>;
    expect(Object.keys(core).length).toBeGreaterThan(0);
    for (const ns of Object.keys(core)) {
      expect(en, `en.json has no namespace "${ns}"`).toHaveProperty(ns);
      expect(core[ns]).toEqual(en[ns]);
    }
  });
});

describe("the full bundle is lazy for every language, English included", () => {
  const I18N = read("src/i18n/index.ts");

  it("does not import en.json statically — that was the 86 KB", () => {
    expect(I18N).not.toMatch(/^\s*import\s+en\s+from\s+["']\.\/locales\/en\.json["']/m);
    expect(I18N).toContain('import enCore from "./locales/en.core.json"');
  });

  it("lists en beside es and nl as a dynamic import", () => {
    expect(I18N).toMatch(/en:\s*\(\)\s*=>\s*import\("\.\/locales\/en\.json"\)/);
    expect(I18N).toMatch(/es:\s*\(\)\s*=>\s*import\("\.\/locales\/es\.json"\)/);
    expect(I18N).toMatch(/nl:\s*\(\)\s*=>\s*import\("\.\/locales\/nl\.json"\)/);
  });

  it("initialises i18next with the CORE, not the full bundle", () => {
    expect(I18N).toContain("resources: { en: { translation: enCore } }");
  });

  it("exports a promise that also waits for English, the fallback language", () => {
    // Every other language falls through to en for a key it lacks. Waiting only
    // for the active language would let a Spanish page paint an English key's
    // NAME wherever es.json is incomplete.
    expect(I18N).toContain("export const localeReady");
    expect(I18N).toMatch(/loadLocale\("en"\)/);
  });
});

describe("LocaleGate", () => {
  // COMMENTS STRIPPED. App.tsx explains the lazy layouts by quoting the markup
  // they sit in — "the same `<Suspense>` that already wraps `<Routes>`" — and an
  // ordering check run over the prose finds that mention first and concludes the
  // gate is in the wrong place. This repo keeps stripComments for exactly this.
  const APP = stripComments(read("src/App.tsx"));

  it("wraps the routes, so no page can paint before its words arrive", () => {
    expect(APP).toContain("<LocaleGate>");
    expect(APP).toContain("</LocaleGate>");
    const gateStart = APP.indexOf("<LocaleGate>");
    const gateEnd = APP.indexOf("</LocaleGate>");
    const routesStart = APP.indexOf("<Routes>");
    const routesEnd = APP.indexOf("</Routes>");
    expect(gateStart).toBeLessThan(routesStart);
    expect(gateEnd).toBeGreaterThan(routesEnd);
  });

  it("falls back to the loader the lazy routes already showed, not a new state", () => {
    // The point of reusing PageLoader: on a cold visit the user sees exactly what
    // they saw before this change — one loader, for slightly longer.
    const gate = APP.slice(APP.indexOf("function LocaleGate"), APP.indexOf("const AdminLayout"));
    expect(gate).toContain("<PageLoader />");
  });

  it("is inside the Suspense boundary, so the shell keeps rendering around it", () => {
    const suspense = APP.indexOf("<Suspense fallback={<PageLoader />}>");
    expect(suspense).toBeGreaterThan(-1);
    expect(APP.indexOf("<LocaleGate>")).toBeGreaterThan(suspense);
  });
});
