import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import { initSentry } from "./lib/sentry";
import { initWebVitalsReporting } from "./lib/webVitals";
import { applyStoredTextSize } from "./lib/textSize";
/*
  SELF-HOSTED WEBFONTS, imported before the design system that uses them.

  index.html used to carry a render-blocking <link> to fonts.googleapis.com. It
  never worked in production: this site's own Content-Security-Policy allows
  `style-src 'self' 'unsafe-inline'` and `font-src 'self' data:` — neither of
  which permits fonts.googleapis.com or fonts.gstatic.com. So the browser was
  told to preconnect to two third parties and then fetch a stylesheet it was
  forbidden to apply, and every page has been rendering in the system fallback
  while paying for the round trips.

  Generated by scripts/perf/fetch-fonts.mjs — latin and latin-ext only.
*/
import "./styles/fonts.css";
import "./index.css";
import "./i18n";
import App from "./App.tsx";

// Initialize Sentry before rendering
initSentry();

// R10's A/A choice, applied BEFORE the first paint. In an effect it would render at the default
// size and then jump, which for a member who chose the large size is the app appearing to ignore
// them once per visit.
applyStoredTextSize();

createRoot(document.getElementById("root")!).render(
  <StrictMode>
    <App />
  </StrictMode>
);

// Start web vitals monitoring after render
initWebVitalsReporting();
