-- ============================================================
-- Staff Rebuild Migration — SUPERSEDED
-- ============================================================
-- This migration is intentionally a no-op.
--
-- The original migration attempted to convert staff.is_active to a
-- generated column, but failed because 6 RLS policies on other tables
-- depended on it. The author wrote a fixed replacement 51 minutes
-- later (20260301135110_1fbef178-...sql) which supersedes this one
-- entirely — it drops the dependent policies first, performs the
-- same column conversion, and recreates all the policies using
-- the new is_staff()/is_admin() helpers.
--
-- On fresh database setups (like Care Conneqt), the original
-- migration would block the push. This no-op version allows the
-- migration chain to complete cleanly while the v2 migration
-- (135110) does the actual work.
--
-- Original intent: see 20260301135110_*.sql (identical body).
-- ============================================================

SELECT 1 WHERE FALSE;  -- explicit no-op
